{
	des: 'Login',
	method: 'POST',
	url: 'http://localhost:9000/login',
	requestHeader: {
		'content-type': 'application/json',
		'pj': '5895824239575601e851f496'
	},
	requestBody: {
		username: 'thanh7',
		password: '123'
	}
}

{
	des: 'Ping to renew session expired',
	method: 'HEAD',
	url: 'http://localhost:9000/ping',
	requestHeader: {
		'content-type': 'application/json',
		'token': '5895824239575601e851f496-58958376d6ebf50434defae4-58958416cbb27e1f789a2a8c'
	}
}

{
	des: 'Check authoriz',
	method: 'HEAD',
	url: 'http://localhost:9000/authoriz',
	requestHeader: {
		'content-type': 'application/json',
		'token': '5895824239575601e851f496-58958376d6ebf50434defae4-5895848bb4e9c614e8d813c1',
		'path': '/Login',
		'actions': 'ADD',
	}
}

{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:9000/accounts?auto_login=1',
	requestHeader: {
		'content-type': 'application/json',
		pj: '5895824239575601e851f496'
	},
	requestBody: {
		role_ids: ['5895825239575601e851f497'],
		username: 'thanh7',
		password: '123',
		status: 1,
		recover_by: 'doanthuanthanh88@gmail.com',
		more: {
			fullname: null
		},
		created_at: new Date(),
		updated_at: new Date()
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:9000/accounts?project_id=5895824239575601e851f496'
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9000/accounts/58940ae5ec50fe166c9835c5',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		project_id: '58940acfec50fe166c9835c3',
		role_ids: ['58940ad8ec50fe166c9835c4'],
		username: 'thanh',
		password: '123',
		status: 1,
		recover_by: 'doanthuanthanh88@gmail.com',
		more: {
			fullname: null
		}
	}
}

{
	des: 'Get detail me',
	method: 'GET',
	url: 'http://localhost:9000/me',
	requestHeader: {
		token: '58940acfec50fe166c9835c3-58940ae5ec50fe166c9835c5-5894450c645b733fa4e9f546'
	}
}

{
	des: 'Update me',
	method: 'PUT',
	url: 'http://localhost:9000/me',
	requestHeader: {
		'content-type': 'application/json',
		token: '58940acfec50fe166c9835c3-58940ae5ec50fe166c9835c5-5894450c645b733fa4e9f546'
	},
	requestBody: {
		recover_by: 'doanthuanthanh88@gmail.com',
		more: {
			fullname: 'thanh pro'
		}
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:9000/accounts/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:9000/accounts/ITEM_ID'
}