{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:9600/account?auto_login=1',
	requestHeader: {
		'content-type': 'application/json',
		pj: '58997ac77e9a4435508973bf'
	},
	requestBody: {
		role_ids: ['58997b0a7e9a4435508973c1'],
		username: 'thanh13',
		password: '123',
		status: 1,
		recover_by: 'doanthuanthanh88@gmail.com',
		more: {
			fullname: 'thanh'
		}
	}
}

{
	method: 'POST',
	url: 'http://localhost:9600/login',
	requestHeader: {
		'content-type': 'application/json',
		pj: '58997ac77e9a4435508973bf'
	},
	requestBody: {
		username: 'thanh13',
		password: '123'
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:9600/account'
}

{
	method: 'HEAD',
	url: 'http://localhost:9600/authoriz',
	requestHeader: {
		'content-type': 'application/json',
		token: '58997ac77e9a4435508973bf-589980092d24aa1dbc5f97ea-589981790911a43cd0e30753',
		path: '/Login',
		actions: 'ADD'
	}
}

{
	method: 'HEAD',
	url: 'http://localhost:9600/ping',
	requestHeader: {
		'content-type': 'application/json',
		token: '58997ac77e9a4435508973bf-589980092d24aa1dbc5f97ea-589980fa82577e1d985d1813'
	}
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9600/account/589847ee491cef29dc41ea2b',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		password: '123',
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:9600/account/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:9600/account/ITEM_ID'
}