{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:9000/account',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		project_id: '58981cad5fb8162318d41c37',
		role_ids: ['58981d254f7f0935948857ee'],
		username: 'thanh',
		password: '123',
		status: 1,
		recover_by: 'doanthuanthanh88@gmail.com',
		more: {
			fullname: 'thanh'
		}
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:9000/account'
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9000/account/ITEM_ID',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		project_id: ,
		role_ids: [],
		app: '',
		username: '',
		password: '',
		status: 0,
		recover_by: '',
		more: {},
		token:
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:9000/account/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:9000/account/ITEM_ID'
}