{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:9000/role',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		project_id: ,
		name: '',
		api: [],
		web: [],
		mob: []
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:9000/role'
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9000/role/ITEM_ID',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		project_id: ,
		name: '',
		api: [],
		web: [],
		mob: []
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:9000/role/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:9000/role/ITEM_ID'
}