{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:9600/role',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		project_id: '58997ac77e9a4435508973bf',
		name: 'User',
		api: [
			{
				path: '/login',
				actions: ['LOGIN']
			}
		],
		web: [],
		mob: []
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:9600/role?project_id=58997ac77e9a4435508973bf'
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9600/role/58981d254f7f0935948857ee',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		name: 'User',
		api: [{
			"path": ".*",
			"actions": [
				".*"
			]
		}],
		web: [],
		mob: []
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:9600/role/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:9600/role/ITEM_ID'
}